<script	src="<?php echo $this->static;?>/js//libs/highcharts/highcharts.js"	type="text/javascript"></script>
<script	src="<?php echo $this->static;?>/js/libs/highcharts/hightheme.js"	type="text/javascript"></script>
<link type="text/css" rel="stylesheet"	href="<?php echo $this->static;?>/styles/treeGrid.css" />
<link type="text/css" rel="stylesheet"	href="<?php echo $this->static;?>/styles/oss.css" />
<!--页面位置-->
<h3 class="location f14">
	<?php echo $this->menu(); ?>
</h3>
<div id="table_warp" class="product_detail mt22">
	<input id="queryString" type="hidden"	value="<?php echo $this->queryString;?>" />
	<form action="/analyze/index/region" id="search_form">
		<div class="product_detail_search clearfix">
			<div class="chart_index fl f14">
				<span period="current_month"
					<?php if($this->period == 'current_month'):?> class="on"
					<?php endif;?>>本月</span> <span period="last_month"
					<?php if($this->period == 'last_month'):?> class="on"
					<?php endif;?>>上月</span> <span period="seven_days"
					<?php if($this->period == 'seven_days'):?> class="on"
					<?php endif;?>>近7天</span> <span
					class="last <?php if($this->period == 'thirty_days'):?>on<?php endif;?>"
					period="thirty_days">近30天</span>
			</div>
			<div class="fl system_drop clearfix">
				<select id="cang_assort" class="cpy_style cang_assort"
					name="enterprise" style="width: 185px;">
					<?php if($this->enterprises):?>
					<?php foreach($this->enterprises as $id => $enterprise):?>
					<option value="<?php echo $id?>"
						<?php if($this->enterprise_id == $id):?> selected="selected"
						<?php endif;?>>
						<?php echo mb_strimwidth($enterprise,0,26,'...')?>
					</option>
					<?php endforeach;?>
					<?php endif?>
				</select>
			</div>
			<div class="fl system_drop clearfix">
				<select id="produt_assort" class="cpy_style product_assort"
					name="product" style="width: 120px;">
					<?php if(!empty($this->products['list'])):?>
					<?php foreach($this->products['list'] as $item):?>
					<option value="<?php echo $item['id']?>"
						<?php if($this->product_id == $item['id']):?> selected="selected"
						<?php endif;?>>
						<?php echo mb_strimwidth($item['name'],0,16,'...')?>
					</option>
					<?php endforeach;?>
					<?php else:?>
					<option value="">此商家暂无产品</option>
					<?php endif;?>
				</select>
			</div>
			<div class="chart_search f14 fl">
				<input type="text" name="start_date" class="time_pick"
					id="timer_from" readonly="readonly"
					value="<?php echo isset($this->start_date) ? $this->start_date : ''?>" />
				<label> - </label> <input type="text" name="end_date"
					class="time_pick" id="timer_to" readonly="readonly"
					value="<?php echo isset($this->end_date) ? $this->end_date : ''?>" />
			</div>
			<div class="console_search_wrap fr">
				<a type="submit" onFocus="blur();" id="search"
					class="f16 clF tc ml10 search_icon_btn" href="javascript:void(0)"><i
					class="find_icon"></i>查 询</a>
			</div>
		</div>
	</form>
	<div class=" mt24 f14">
		<div class="product_detail_search clearfix">
			<div class="chart_index fl f14 ml10">
				<span chart_line="add" class="on">新增数</span> <span chart_line="all">累计数</span>
			</div>
		</div>
		<div id="chart" class="vertical_nav"
			style="height: 700px; margin-bottom: 10px"></div>
		<table id="treeGrid" resizeWidth="resizeWidth"
			resizeHeight="resizeHeight" rowNum="false" height="500"
			datasource="treeGridDatasource" treeField="name"
			onCellStyleRender="onCellStyleRender"
			onCellContentRender="onCellContentRender" collapse="true"
			onExpand="false">
			<thead>
				<tr>
					<th field="name" align="center">地域</th>
					<th field="data" width="150" align="right">设备新增</th>
					<th field="dataAll" width="150" align="right">设备累计</th>
				</tr>
			</thead>
		</table>
		<div class="mt10"></div>
	</div>
</div>
<div id="tips_dialog" style="display: none;" title="系统提醒">
	<p class="message_text" id="tips_msg"></p>
</div>
<script type="text/javascript"
	src="<?php echo $this->static;?>/js/treeGrid.min.js"></script>
<script type="text/javascript">
    $(function(){
        $( "#tips_dialog" ).dialog({
            autoOpen: false,
            width: 555,
            dialogClass: "my-dialog",
            modal: true,
            show: {
                effect: "blind",
                duration: 300
            },
            hide: {
                effect: null,
                duration: 500
            },
            buttons: {
                "确定": function() {
                    $( this ).dialog( "close" );
                }
            }
        });
        //datepicker
        (function(){
            var config={
                changeMonth: true,
                changeYear: true,
                rangeSelect: true,
                yearRange: '-10:+10',
                currentText: "Now"
            }
            $("#timer_from").datepicker(config);
            $("#timer_to").datepicker(config);
        })();

        Highcharts.setOptions({
            chart: {
                backgroundColor: {
                    linearGradient: [0, 0, 500, 500],
                    stops: [
                        [0, 'rgb(255, 255, 255)'],
                        [1, 'rgb(255, 255, 255)']
                        ]
                },
                borderWidth: 1,
                borderColor:'#adadad',
                plotBackgroundColor: 'rgba(255, 255, 255, .9)',
                plotShadow: false,
                plotBorderWidth: 1,
            }
        });
        
        var charts = new Highcharts.Chart({
            chart: {
                renderTo: 'chart',
                defaultSeriesType: 'column',
                inverted: true
            },
            title: {
                text: '新增数',
                x: -20 //center
            },
            subtitle: {
                x: -20
            },
            xAxis: {
                categories: <?php echo $this->chartsX;?>,
                tickInterval: 1,
                tickmarkPlacement:'on'
            },
            yAxis: {
                title: {
                    text: '数量',
                    x: 10, //center
                    style:{
                        writingMode:'lr-tb'
                    },
                    rotation : 0,
                    offset : 50 //标题离图表左边的距离
                },
                plotLines: [{
                    value: 0,
                    width: 1,
                    color: '#808080'
                }],
                minorGridLineWidth : 0
            },
            legend: {
                layout: 'vertical',
                align: 'right',
                verticalAlign: 'middle',
                borderWidth: 0
            },
            series: [
                {
                    name: '新增数',
                    data: <?php echo $this->chartsPerioad;?>},
                {
                    name: '累计数',
                    data: <?php echo $this->chartsAll;?>}
            ]
        });
        charts.series[1].hide();
        $('span[chart_line]').click(function () {
            var line_map = {
                'add':0,
                'all':1
            }
            charts.setTitle({text:charts.series[line_map[$(this).attr('chart_line')]].name});
            $('span[chart_line]').attr('class','');
            $(this).attr('class','on');
            for(var item in line_map) {
                charts.series[line_map[item]].hide();
            }
            charts.series[line_map[$(this).attr('chart_line')]].show();
        });

        $('span[period]').click(function () {
            var period = $(this).attr('period');
            location.href = '/analyze/index/region<?php echo $this->base_url?>&period='+period;
        });
        $('#search').click(function () {
            var start_date = new Date($('#timer_from').val());
            var end_date = new Date($('#timer_to').val());
            var today = new Date();
            if(end_date > today || start_date > today) { // 开始时间不能大于结束时间
                $('#tips_msg').text('选定时间不能超过今天！');
                $( "#tips_dialog" ).dialog( "open" );
                return false;
            }
            if(start_date > end_date) { // 开始时间不能大于结束时间
                $('#tips_msg').text('开始时间不能大于结束时间！');
                $( "#tips_dialog" ).dialog( "open" );
                return false;
            }

            var diff_days = countTimeLength('d',$('#timer_from').val(),$('#timer_to').val());
            if(diff_days > 60) {
                $('#tips_msg').text('抱歉，时间跨度不能超过60天！');
                $( "#tips_dialog" ).dialog( "open" );
                return false;
            }
            if($('#produt_assort option:selected').val() == '') {
                $('#tips_msg').text('抱歉，请选择需要查询的产品！');
                $( "#tips_dialog" ).dialog( "open" );
                return false;
            }
            $('#search_form').submit();
        });
        $('#cang_assort').change(function () {
            $("#dk_container_produt_assort .dk_options .dk_options_inner").empty();
            $('#dk_container_produt_assort >a').text('正在查询...');
            $('#produt_assort').empty();
            var enterprise_id = $(this).val();
            $.post('/enterprise/index/getproducts/',{enterprise_id:enterprise_id},function (data) {
                if(data.result.counts > 0) {
                	var list = data.result.list;
					var name_len = 0;
					var this_name = '';
					for(item in list) {
						this_name = list[item]['name'];
						name_len = this_name.length;
						if(name_len > 12){
							this_name = cutstr(this_name, 12);
						}
						$("#produt_assort").append("<option value=\""+ list[item]['id'] + "\">"+ this_name +"</option>");
						$("#dk_container_produt_assort .dk_options .dk_options_inner").append("<li><a data-dk-dropdown-value=\""+ list[item]['id'] +"\">"+ this_name +"</a></li>");
						if(item == 0) { // 第一个元素放到列表的一个位置  <a class="dk_toggle dk_label" style="width: 218px;">美的电风扇</a>
							$('#dk_container_produt_assort >a').text(this_name);
						}
					}
                } else {
                    $("#produt_assort").append("<option value=\"\">此商家暂无产品</option>");
                    $('#dk_container_produt_assort >a').text('此商家暂无产品！');
                }
            },'json');
        });
        TreeGrid.scan("#treeGrid");
    })

    //渲染中间散列的字体颜色
    function onCellStyleRender(value,rowData,field){
        if(field==="PercentComplete" || field==="Duration" || field==="Start" ){
            return 'color:#acacac';
        }
        if(field ==="operate"){
            return 'color:#216ed9';
        }
    };
    //定义表格的宽度
    function resizeWidth(){
        return $("#table_warp").width() - 18;
    };
    //定义表格的高度
    function resizeHeight(){
        return $(window).height() - 200;
    }
    //设置表格的数据
    function treeGridDatasource (obj){
        $.get('/analyze/index/gettree?tree=1&' + $('#queryString').val(), function(data){
            if(data.status == 200) {
                obj.setDatasource(TreeGrid.listToTree(data.result,"id","pid"));
            }
        },'json');
    }

</script>
