<script	src="<?php echo $this->static;?>/js//libs/highcharts/highcharts.js"	type="text/javascript"></script>
<script	src="<?php echo $this->static;?>/js/libs/highcharts/hightheme.js"	type="text/javascript"></script>
<!--页面位置-->
<h3 class="location f14">
	<?php echo $this->menu(); ?>
</h3>
<div class="product_detail mt22">
	<form action="/analyze/index/time" id="search_form">
		<div class="product_detail_search clearfix">

			<div class="fl system_drop clearfix">
				<select id="cang_assort" class="cpy_style cang_assort"
					name="enterprise" style="width: 185px;">
					<?php if($this->enterprises):?>
					<?php foreach($this->enterprises as $id => $enterprise):?>
					<option value="<?php echo $id?>"
						<?php if($this->enterprise_id == $id):?> selected="selected"
						<?php endif;?>>
						<?php echo mb_strimwidth($enterprise,0,16,'...')?>
					</option>
					<?php endforeach;?>
					<?php endif?>
				</select>
			</div>
			<div class="fl system_drop clearfix">
				<select id="produt_assort" class="cpy_style product_assort"
					name="product" style="width: 120px;">
					<?php if(!empty($this->products['list'])):?>
					<?php foreach($this->products['list'] as $item):?>
					<option value="<?php echo $item['id']?>"
						<?php if($this->product_id == $item['id']):?> selected="selected"
						<?php endif;?>>
						<?php echo mb_strimwidth($item['name'],0,16,'...')?>
					</option>
					<?php endforeach;?>
					<?php else:?>
					<option value="">此商家暂无产品！</option>
					<?php endif;?>
				</select>
			</div>
			<div class="chart_search f14 fl">
				<input type="text" class="time_pick" id="start_date"
					readonly="readonly" value="<?php echo date('Y-m-d');?>"
					style="display: none" /> <input type="text" name="start_date"
					value="<?php echo isset($this->start_date) ? $this->start_date : ''?>"
					class="time_pick" id="end_date"
					style="width: 120px; ime-mode: disabled" />
			</div>
			<div class="console_search_wrap fr">
				<a type="submit" onFocus="blur();" id="search"
					class="f16 clF tc ml10 search_icon_btn" href="javascript:void(0)"><i
					class="find_icon"></i>查 询</a>
			</div>
		</div>
	</form>
	<div class="product_table progressbar_table mt24 f14">
		<div id="chart" class="vertical_nav"></div>
		<table class="table_s tc tc_left" width="100%" border="0">
			<thead>
				<tr>
					<td width="160px">使用时段</td>
					<td style="text-align: right; width: 150px;">设备数</td>
					<td>占比</td>
				</tr>
			</thead>
			<tbody>
				<?php if($this->data):?>
				<?php foreach($this->data as $k=>$v):?>
				<tr>
					<td><?php echo $this->tableIndex[$k]; ?></td>
					<td style="text-align: right;"><?php echo $v;?></td>
					<td><?php echo $this->dataSum==0?'0%':number_format($v/$this->dataSum*100,0).'%';?></td>
				</tr>
				<?php
                            endforeach;?>
				<?php else:?>
				<tr>
					<td colspan="3" style="text-align: center;">暂无记录</td>
				</tr>
				<?php endif;?>
			</tbody>
		</table>
	</div>
</div>
<div id="tips_dialog" style="display: none;" title="系统提醒">
	<p class="message_text" id="tips_msg"></p>
</div>
<script type="text/javascript">
    $(function(){        
        $("#start_date").datepicker({
            changeMonth: true,
            changeYear: true,
            rangeSelect: true,
            yearRange: '-10:+10',
            maxDate: '+0y +0m -1d',
            onClose: function( selectedDate ) {
                $( "#end_date" ).datepicker( "option", "minDate", selectedDate );
            }
        });
        $("#end_date").datepicker({
            changeMonth: true,
            changeYear: true,
            rangeSelect: true,
            yearRange: '-10:+10',
            maxDate: '+0y +0m -1d',
            onClose: function( selectedDate ) {
                $( "#start_date" ).datepicker( "option", "maxDate", selectedDate );
            }
        });

        Highcharts.setOptions({
            chart: {
                backgroundColor: {
                    linearGradient: [0, 0, 500, 500],
                    stops: [
                        [0, 'rgb(255, 255, 255)'],
                        [1, 'rgb(255, 255, 255)']
                        ]
                },
                borderWidth: 1,
                borderColor:'#adadad',
                plotBackgroundColor: 'rgba(255, 255, 255, .9)',
                plotShadow: false,
                plotBorderWidth: 1,
            }
        });
        
        $('#chart').highcharts({
            chart: {
                defaultSeriesType: 'column'
            },
            title: {
                text: '时间段分布',
                x: -20 //center
            },
            subtitle: {
                x: -20
            },
            xAxis: {
                categories: <?php echo $this->chartsX;?>,
                tickInterval: 1,
                tickmarkPlacement:'on'
            },
            yAxis: {
                title: {
                    text: '数量',
                    x: 10, //center
                    style:{
                        writingMode:'lr-tb'
                    },
                    rotation : 0,
                    offset : 50 //标题离图表左边的距离
                },
                plotLines: [{
                    value: 0,
                    width: 1,
                    color: '#808080'
                }],
                minorGridLineWidth : 0
            },
            legend: {
                layout: 'vertical',
                align: 'right',
                verticalAlign: 'middle',
                borderWidth: 0
            },
            series: [{
                name: '时间段分布',
                data: <?php echo $this->chartsData;?>}]
        });

        $('#cang_assort').change(function () {
            $("#dk_container_produt_assort .dk_options .dk_options_inner").empty();
            $('#dk_container_produt_assort >a').text('正在查询...');
            $('#produt_assort').empty();
            var enterprise_id = $(this).val();
            $.post('/enterprise/index/getproducts/',{enterprise_id:enterprise_id},function (data) {
                if(data.result.counts > 0) {
                	var list = data.result.list;
					var name_len = 0;
					var this_name = '';
					for(item in list) {
						this_name = list[item]['name'];
						name_len = this_name.length;
						if(name_len > 12){
							this_name = cutstr(this_name, 12);
						}
						$("#produt_assort").append("<option value=\""+ list[item]['id'] + "\">"+ this_name +"</option>");
						$("#dk_container_produt_assort .dk_options .dk_options_inner").append("<li><a data-dk-dropdown-value=\""+ list[item]['id'] +"\">"+ this_name +"</a></li>");
						if(item == 0) { // 第一个元素放到列表的一个位置  <a class="dk_toggle dk_label" style="width: 218px;">美的电风扇</a>
							$('#dk_container_produt_assort >a').text(this_name);
						}
					}
                } else {
                    $("#produt_assort").append("<option value=\"\">此商家暂无产品</option>");
                    $('#dk_container_produt_assort >a').text('此商家暂无产品！');
                }
            },'json');
        });

        $('#search').click(function () {
            var start_date = new Date($('#start_date').val());
            var today = new Date();
            if( start_date > today) { // 开始时间不能大于结束时间
                $('#tips_msg').text('选定时间不能超过今天！');
                $( "#tips_dialog" ).dialog( "open" );
                return ;
            }

            if($('#produt_assort option:selected').val() == '') {
                $('#tips_msg').text('抱歉，请选择需要查询的产品！');
                $( "#tips_dialog" ).dialog( "open" );
                return false;
            }
            $('#search_form').submit();
        });
    })
</script>