<!--页面位置-->
<script type="text/javascript" src="<?php echo $this->static;?>/js/jquery.form.js"></script>
<h3 class="location f14"><?php echo $this->menu('编辑功能', '/ezstudio/action/index'); ?></h3>
	<form class="cmxform"  action="/ezstudio/action/add" method="post" id="form_add_action">
            <table class="detail_tabel psw_table f14 mt20">
                <tr>
                    <td>功能名称：</td>
                    <td><input type="hidden" name="id" value="<?php echo $this->action_info['id']?>">
                        <input type="text" class="cpy_name" value="<?php echo $this->action_info['name']?>" placeholder="请输入功能名称" id="name" name="name" class="required"/>
                    </td>
                </tr>
                <tr>
                    <td>功能标识：</td>
                    <td>
                        <input type="text" class="cpy_name" value="<?php echo $this->action_info['action']?>"  id="action" name="action" placeholder="功能标识，请输入纯字符串" class="required"/>
                    </td>
                </tr>
                <tr>
                    <td>功能描述：</td>
                    <td>
                    	<textarea rows="10" cols="60" class="text_cls" id="description" name="description"><?php echo $this->action_info['description']?></textarea>
                    </td>
                </tr>
                <tr>
                    <td>功能分类：</td>
                    <td class="system_drop">
                    	<select id="category_id" class="cpy_style product_assort" name ="product_category_id">
                           <option value="">选择分类</option>
                          <?php foreach ($this->category as $v) :?>
                               <option value="<?php echo $v['id'];?>" <?php if($v['id'] == $this->action_info['product_category_id']):?>selected="selected" <?php endif;?>><?php echo $v['levelstr'] . $v['name'];?></option>
                          <?php endforeach;?>
                       </select>
                    </td>
                </tr>
                <tr>
                    <td>
                        <a id="save_action"  onfocus="blur();" class="f16 clF tc search_btn brue_btn"  href="javascript:void(0)">保存</a>
                    </td>
                </tr>
</table>
</form>
<div id="message_dialog" style="display:none;" title="系统提醒">
    <p class="message_text">保存成功！</p>
    <a id="close_message"  onfocus="blur();" class="f16 clF tc search_btn brue_btn"  href="javascript:void(0)">确 定</a>
</div>
<div id="tips_dialog" style="display:none;" title="系统提醒">
	<p class="message_text" id="tips_msg"></p>
</div>
<script language="javascript" type="text/javascript">
    $(function() {
    	$( "#tips_dialog" ).dialog({
            autoOpen: false,
            width: 555,
            dialogClass: "my-dialog",
            modal: true,
            show: {
                effect: "blind",
                duration: 300
            },
            hide: {
                effect: null,
                duration: 500
            },
            buttons: {
                "确定": function() {
                	$( this ).dialog( "close" );
        		}
            }
        });
        
        $( "#message_dialog" ).dialog({
            autoOpen: false,
            width: 540,
            height: 240,
            show: {
                effect: "blind",
                duration: 300
            },
            hide: {
                effect: null,
                duration: 500
            },
            dialogClass: "my_message_dialog",
            modal: true
        });
        $("#close_message").on("click",function() {
            $( "#message_dialog" ).dialog( "close" );
            location.href = '/ezstudio/action/index';
        });
	
    	$('#form_add_action').validate({
    		rules: {
    			'name': {
    				required: true,
    				minlength: 2,
    				maxlength:10
    			},
    			'action': {
    				required: true,
    				minlength: 2,
    				maxlength:50
    			},
    			'description': {
    				minlength: 6,
    				maxlength:255
    			},
    			'product_category_id': {
    				required: true
    			}
    		},
    		messages: {   //自定义提示信息
    			
    		}
    	});
    	$('#save_action').click(function () {
			if($('#form_add_action').valid()) {
				$('#form_add_action').ajaxSubmit({
					url:'/ezstudio/action/update', //提交给哪个执行
					type:'POST',
					dataType: 'json',
					success: function (result) {
						if(result.status == 200) {
							$( "#message_dialog" ).dialog( "open" );
						} else {
							$('#tips_msg').text(result.msg);
							$( "#tips_dialog" ).dialog( "open" );
						}
					}
				});
				return false;
			}
		});
})
</script>
