<h3 class="location f14"><?php echo $this->menu(); ?></h3>
<div class="product_detail mt22">
<div class="product_detail_search clearfix">
       <form action="/ezstudio/action/index" method="get"  id="search_form">
                           <div class="product_detail_search clearfix">
                               <div class="fl system_drop clearfix">
                                    <select id="category_id" class="cpy_style product_assort" name ="search[product_category_id]" style="width: 120px;">
                                        <option value="">功能分类</option>
                                      <?php foreach ($this->category as $v) :?>
                                     <option value="<?php echo $v['id'];?>" <?php if($v['id'] == $this->search['product_category_id']):?>selected="selected" <?php endif;?>><?php echo $v['levelstr'] . mb_strimwidth($v['name'],0,14,'...');?></option>
                                     <?php endforeach;?>
                                    </select>
                                </div>
                                <div class="fl system_drop clearfix">
                                   <input type="text" class="cpy_name w150" id="name"  name ="search[name]" value="<?php echo isset($this->search['name']) ? $this->search['name'] : ''?>" placeholder="请输入功能名称">
                               </div>
                               <div class="fl system_drop clearfix">
                                   <input type="text" class="cpy_name w150" id="name"  name ="search[action]" value="<?php echo isset($this->search['action']) ? $this->search['action'] : ''?>" placeholder="请输入功能标识">
                               </div>
                                <div class="console_search_wrap clearfix fr"><a class="search_icon_btn f16 clF tc" onFocus="blur();" href="javascript:;" id="search"><i class="find_icon"></i>查 询</a></div>
                           </div>
                           </form>
                           
</div>
<div class="product_detail_display">
									<div class="product_table mt24 f14">
									<div class="product_detail_search clearfix">
									<div class="console_search_wrap fr mr10" style="margin-top:8px"><a class="f16 clF tc search_btn ml16" onFocus="blur();" href="javascript:;" id="add">添 加</a></div>
									</div>
                                       <table class="table_s tc mt24 tc_left auto_table_len" width="100%" border="0">
                                         <thead>
                                          <tr>
                                            <td width="60px">编号</td>
                                            <td>功能</td>
                                            <td width="200px">标识</td>
                                            <td width="200px">功能分类</td>
                                            <td style="text-align: center;width:200px;">操作</td>
                                          </tr>
                                         </thead>
                                         <tbody>
                                         <?php if($this->action_list):?>
                                         	<?php foreach($this->action_list as $item):?>
                                         	<tr>
                                            <td><?php echo $item['id']?></td>
                                            <td>
                                            <?php echo $this->escape($item['name'])?>
                                            </td>
                                            <td><?php echo $this->escape($item['action'])?></td>
                                            <td><?php echo isset($this->category_map[$item['product_category_id']]) ? $this->category_map[$item['product_category_id']]['name'] : '[分类已删除]'?></td>
                                            <td class="cl0b9600" style="text-align: center;"><a href="/ezstudio/action/detail?id=<?php echo $item['id']?>">编辑</a> | <a href="javascript:void(0)" delete_id="<?php echo $item['id']?>">删除</a></td>
                                           </tr>
                                         	<?php endforeach;?>
                                         	<?php else:?>
                                         	<tr><td colspan="5" style="text-align: center;">暂无记录</td></tr>
                                         <?php endif;?>
                                         </tbody>
                                   </table>
                                </div>
               <?php echo $this->paginationControl($this->pagenation, 'Elastic', 'pagelist.phtml',array('base_url'=>$this->base_url)); ?>
          </div>
</div>
<div id="confirm_dialog" style="display:none;" title="系统提醒">
<p class="message_text">您确认删除此条记录吗？</p>
</div>
<script language="javascript" type="text/javascript">
	$(function () {
		var delete_id = 0;
		$( "#confirm_dialog" ).dialog({
            autoOpen: false,
            width: 555,
            dialogClass: "my-dialog",
            modal: true,
            show: {
                effect: "blind",
                duration: 300
            },
            hide: {
                effect: null,
                duration: 500
            },
            buttons: {
                "取消": function() {
                    $( this ).dialog( "close" );
                },
                "确定": function() {
                	$.post('/ezstudio/action/delete', {id:delete_id}, function (result) {
                		if (result.msg == 505) {
                            $('#confirm_dialog .message_text').text('亲，你没有这个操作的权限！');
                            $("#confirm_dialog").dialog("open");
                            return false;
                		}
        				location.href = '/ezstudio/action/index';
        			},'json');
                }
            }
        });

		$('#search').click(function () {
			$('#search_form').submit();
		});
		
		$('#add').click(function () {
			location.href = '/ezstudio/action/add';
		});

		$('a[delete_id]').click(function () {
			delete_id = $(this).attr('delete_id');
			$( "#confirm_dialog" ).dialog( "open");
		});
	});
</script>
