<!--页面位置-->
<script type="text/javascript" src="<?php echo $this->static;?>/js/jquery.form.js"></script>
<script type="text/javascript" src="<?php echo $this->static;?>/js/libs/swfupload/swfupload.js"></script>
<script type="text/javascript" src="<?php echo $this->static;?>/js/libs/swfupload/swfupload.queue.js"></script>
<script type="text/javascript" src="<?php echo $this->static;?>/js/libs/swfupload/fileprogress.js"></script>
<script type="text/javascript" src="<?php echo $this->static;?>/js/libs/swfupload/handlers.js"></script>
<h3 class="location f14"><?php echo $this->menu('添加控件','/ezstudio/control/index'); ?></h3>
	<form class="cmxform"  action="/ezstudio/control/add" method="post" id="form_add_action">
            <table class="detail_tabel psw_table f14 mt20">
                <tr>
                    <td>控件名称：</td>
                    <td>
                        <input type="text" class="cpy_name" placeholder="请输入功能名称" id="name" name="name" class="required"/>
                    </td>
                </tr>
                <tr>
                    <td>控件标签：</td>
                    <td>
                        <input type="text" class="cpy_name" placeholder="请输入字母数字组合的控件标签" id="label" name="label" class="required"/>
                    </td>
                </tr>
                <tr>
					<td>控件icon：</td>
					<td>
					<span class="fieldset flash" id="fsUploadProgress_icon"></span>
					<span id="upload_status_icon"></span>
					<a  id="upload_icon" class="f14 clF tc search_btn brue_btn ml56" onfocus="blur();" href="javascript:void(0)">上传</a>
					<input id="btnCancel_icon" type="button" value="取消上传" disabled="disabled" style="display:none" />
					<input type="hidden" name="icon" id="icon" value="">
					</td>
				</tr>
                <tr>
                    <td>控件类型：</td>
                    <td class="system_drop">
                    	<select id="control_type_id" class="cpy_style product_assort" name ="control_type_id">
                          <?php foreach ($this->type_map as $v) :?>
                               <option value="<?php echo $v['id'];?>"><?php echo $v['name'];?></option>
                          <?php endforeach;?>
                       </select>
                    </td>
                </tr>
                <tr>
                    <td>功能描述：</td>
                    <td>
                    	<textarea rows="8" cols="60" class="text_cls mt10" id="description" name="description"></textarea>
                    </td>
                </tr>
                <tr>
                    <td>JS代码：</td>
                    <td>
                    	<textarea rows="8" cols="60" class="text_cls mt10" id="js_code" name="js_code" class="required"></textarea>
                    </td>
                </tr>
                <tr>
                    <td>Selected代码：</td>
                    <td>
                    	<textarea rows="8" cols="60" class="text_cls mt10" id="selected_code" name="selected_code"></textarea>
                    </td>
                </tr>
                <tr>
                    <td>DOM代码：</td>
                    <td>
                    	<textarea rows="8" cols="60" class="text_cls mt10" id="dom_code" name="dom_code" class="required"></textarea>
                    </td>
                </tr>
                
                <tr>
                    <td>
                        <a id="save_action"  onfocus="blur();" class="f16 clF tc search_btn brue_btn"  href="javascript:void(0)">保存</a>
                    </td>
                </tr>
</table>
</form>
<div id="message_dialog" style="display:none;" title="系统提醒">
    <p class="message_text">保存成功！</p>
    <a id="close_message"  onfocus="blur();" href="javascript:void(0)" class="f16 clF tc search_btn brue_btn" >确 定</a>
</div>
<div id="tips_dialog" style="display:none;" title="系统提醒">
	<p class="message_text" id="tips_msg"></p>
</div>
<script language="javascript" type="text/javascript">
    $(function() {
    	$( "#tips_dialog" ).dialog({
            autoOpen: false,
            width: 555,
            dialogClass: "my-dialog",
            modal: true,
            show: {
                effect: "blind",
                duration: 300
            },
            hide: {
                effect: null,
                duration: 500
            },
            buttons: {
                "确定": function() {
                	$( this ).dialog( "close" );
        		}
            }
        });
        
        $( "#message_dialog" ).dialog({
            autoOpen: false,
            width: 540,
            height: 240,
            show: {
                effect: "blind",
                duration: 300
            },
            hide: {
                effect: null,
                duration: 500
            },
            dialogClass: "my_message_dialog",
            modal: true
        });
        $("#close_message").on("click",function() {
            $( "#message_dialog" ).dialog( "close" );
			location.href = '/ezstudio/control/index';
        });
	
    	$('#form_add_action').validate({
    		rules: {
    			'name': {
    				required: true,
    				minlength: 2,
    				maxlength:150
    			},
    			'label': {
    				required: true,
    				minlength: 2,
    				maxlength:32
    			},
    			'js_code': {
    				minlength: 5
    			},
    			'dom_code': {
    				required: true,
    				minlength: 5
    			},
    			'description': {
    				minlength: 6,
    				maxlength:512
    			}
    		},
    		messages: {   //自定义提示信息
    			
    		}
    	});
    	$('#save_action').click(function () {
			if($('#form_add_action').valid()) {
				$('#form_add_action').ajaxSubmit({
					url:'/ezstudio/control/add', //提交给哪个执行
					type:'POST',
					dataType: 'json',
					success: function (result) {
						if(result.status == 200) {
							$( "#message_dialog" ).dialog( "open" );
						} else if (result.msg == 505) {
                            $('#message_dialog .message_text').text('亲，你没有这个操作的权限！');
                            $("#message_dialog").dialog("open");
                		} else {
							$('#tips_msg').text(result.msg);
							$( "#tips_dialog" ).dialog( "open" );
						}
					}
				});
				return false;
			}
		});
    	//icon上传
    	var settings = {
				flash_url : "<?php echo $this->static;?>/js/libs/swfupload/swfupload.swf",
				upload_url: "/api/upload/index",
				post_params: {"type" : "control"},
				file_size_limit : "2 MB",
				file_types : "*.*",
				file_types_description : "All Files",
				file_upload_limit : 100,  //配置上传个数
				file_queue_limit : 1,
				custom_settings : {
					progressTarget : "fsUploadProgress_icon",
					cancelButtonId : "btnCancel_icon",
					ProgressStatusId:'upload_status_icon'
				},
				debug: false,
				button_window_mode:'Opaque',
				// Button settings
				button_image_url: "<?php echo $this->static;?>/images/TestImageNoText_65x29.png",
				button_width: "65",
				button_height: "29",
				button_placeholder_id: "upload_icon",
				button_text: '<span class="falsh_upload_button">上传</span>',
				button_text_style: '.falsh_upload_button{color:#FFFFFF;}',
				button_text_left_padding: 16,
				button_text_top_padding: 5,
				button_text_top_margin: 10,
				file_queued_handler : fileQueued,
				file_queue_error_handler : fileQueueError,
				file_dialog_complete_handler : fileDialogComplete,
				upload_error_handler : uploadError,
				upload_success_handler : function(file, serverData) {
					try {
						serverData = eval("("+ serverData +")");
						var progress_div_id = this.customSettings.progressTarget;
						var progress = new FileProgress(file, progress_div_id);
						progress.setComplete();
						progress.setStatus("上传成功");
						progress.toggleCancel(false);
						var img = '<img  src="'+ serverData.result.url +'" class="cut_make_up" width="100" height="100">';
						var link = '<a target="_blank" href="'+ serverData.result.url +'">'+ img +'</a>';
						$('#icon').val(serverData.result.path);
						var file_container = '<span class="mr10">'+ link +'</span>';
						$("#"+progress_div_id).html(file_container);
					} catch (ex) {
						this.debug(ex);
					}
				},
				upload_complete_handler : uploadComplete,
				queue_complete_handler : queueComplete
		};
		var swfu01 = new SWFUpload(settings);
})
</script>
