<!--页面位置-->
<script type="text/javascript" src="<?php echo $this->static;?>/js/jquery.form.js"></script>
<h3 class="location f14"><?php echo $this->menu(); ?></h3>
	<form class="cmxform"  action="" method="post" id="form_account">
            <table class="detail_tabel psw_table f14 mt20">
            	<tr>
                    <td>固件标识：</td>
                    <td>
                        <input type="text" name="name" class="cpy_name" class="required">
                    </td>
                </tr>
                <tr>
                    <td>固件包名称：</td>
                    <td>
                        <input type="text" name="name" class="cpy_name">
                    </td>
                </tr>
                <tr>
                    <td>固件版本号：</td>
                    <td>
                        <input type="text" name="name" class="cpy_name">
                    </td>
                </tr>
                <tr>
                    <td>固件描述：</td>
                    <td>
                        <input type="text" name="name" class="cpy_name">
                    </td>
                </tr>
                <tr>
                    <td>固件包上传：</td>
                    <td>
                        <input type="text" name="name" class="cpy_name">
                    </td>
                </tr>
                <tr>
                    <td>页面示例：</td>
                    <td>
                        <input type="text" name="name" class="cpy_name">
                    </td>
                </tr>
               <tr>
                    <td>更新内容：</td>
                    <td>
                        <input type="text" name="name" class="cpy_name">
                    </td>
                </tr>
                <tr>
                    <td>发布状态：</td>
                    <td>
                        <input type="text" name="name" class="cpy_name">
                    </td>
                </tr>
                <tr>
                    <td>
                        <a id="update_account"  onfocus="blur();" class="f16 clF tc search_btn brue_btn" >提 交</a>
                    </td>
                </tr>
</table>
</form>
<div id="message_dialog" style="display:none;" title="系统提醒">
    <p class="message_text">账户更新成功！</p>
    <a id="close_message"  onfocus="blur();" class="f16 clF tc search_btn brue_btn" >我知道啦！</a>
</div>
<script language="javascript" type="text/javascript">
    $(function(){
        $( "#message_dialog" ).dialog({
            autoOpen: false,
            width: 540,
            height: 240,
            show: {
                effect: "blind",
                duration: 300
            },
            hide: {
                effect: null,
                duration: 500
            },
            dialogClass: "my_message_dialog",
            modal: true
        });
        
        $("#close_message").on("click",function() {
            $( "#message_dialog" ).dialog( "close" );
        });

       $('#form_account').validate({
    		rules: {
    			'real_name': {
    				maxlength:20,
    				minlength:2,
    				required: true,
    			},
    			'department': {
    				required: true,
    				maxlength:20,
    				minlength: 2
    			},
    			'email': {
    				required: true,
    				email:true
    			},
    			'phone': {
    				required: true,
    				isMobile: true,
    			}
    		},
    		messages: {   //自定义提示信息
    			//old_password: "原密码输入错误",
    		}
    	});	

    	$('#update_account').click(function () {
			if($('#form_account').valid()) {
				$('#form_account').ajaxSubmit({
					url:'/system/user/modifyaccount', //提交给哪个执行
					type:'POST',
					dataType: 'json',
					success: function (result) {
						if(result.status == 200) {
							$( "#message_dialog" ).dialog( "open" );
						} else if (result.msg == 505) {
			                $('#message_dialog .message_text').text('亲，你没有这个操作的权限！');
			                $("#message_dialog").dialog("open");
			            }
					}
				});
				return false;
			}
		});
    	
	});
</script>
