<h3 class="location f14"><?php echo $this->menu(); ?></h3>
<div class="product_detail mt22">
                     	<form action="/ezstudio/firmware/mcu" method="get"  id="search_form">
                           <div class="product_detail_search clearfix">
                               <div class="fl system_drop clearfix">
                                    <select id="product_id" class="cpy_style product_assort" name ="search[product_id]" style="width: 120px;">
                                        <option value="">所有产品</option>
                                        <?php foreach($this->product_list as $product):?>
                                        <option value="<?php echo $product['id']?>" <?php if($product['id'] === $this->search['product_id']):?> selected="selected"<?php endif?>><?php echo mb_strimwidth($product['name'],0,18,'...')?></option>
                                        <?php endforeach;?>
                                    </select>
                                </div>
                                <div class="fl system_drop clearfix">
                                   <select id="enterprise_id" class="cpy_style cang_assort" name ="search[enterprise_id]" style="width: 120px;">
                                       <option value="0">所有厂商</option>
                                       <?php foreach($this->enterprise_list as $enterprise):?>
                                        <option value="<?php echo $enterprise['id']?>" <?php if($enterprise['id'] == $this->search['enterprise_id']):?> selected="selected"<?php endif?>><?php echo mb_strimwidth($enterprise['company_name'],0,18,'...')?></option>
                                        <?php endforeach;?>
                                   </select>
                               </div>
                               <div class="fl system_drop clearfix">
                                   <input type="text" class="cpy_name w150" id="name"  name ="search[name]" value="<?php echo isset($this->search['name']) ? $this->search['name'] : ''?>" placeholder="请输入固件名称">
                               </div>
                                <div class="console_search_wrap fr"><a class="search_icon_btn f16 clF tc" onFocus="blur();" href="javascript:;" id="search"><i class="find_icon"></i>查 询</a></div>
                           </div>
                           </form>
                           <div class="product_detail_display">
									<div class="product_table mt24 f14">
                                       <table class="table_s tc tc_left" width="100%" border="0">
                                         <thead>
                                          <tr>                          
                                            <td width="120px">固件ID</td>
                                            <td >产品</td>
                                            <td width="60px">升级标识</td>
                                            <td >固件名</td>
                                            <td width="60px">最新版本</td>
                                            <td>厂商</td>
                                            <td width="60px">发布时间</td>
                                            <td width="60px">版本数</td>
                                            <td width="60px" style="text-align: center;">操作</td>
                                          </tr>
                                         </thead>
                                         <tbody>
                                         <?php if($this->fireware_mcu_list):?>
                                         	<?php foreach($this->fireware_mcu_list as $item):?>
                                         	<tr>
                                            <td><?php echo $item['id']?></td>
                                            <td>
                                            <?php echo $this->product_list[$item['product_id']]['name']?>
                                            </td>
                                            <td><?php echo $this->type_list[$item['upgrade_type_id']]['label']?></td>
                                            <td><?php echo $item['name']?></td>
                                            <td><?php echo $this->version_list[$item['upgrade_type_id']]['last_version']?></td>
                                            <td><?php echo isset($this->enterprise_list[$item['enterprise_id']]) ? $this->enterprise_list[$item['enterprise_id']]['company_name'] : '商家已删除'?></td>
                                            <td><?php echo $this->version_list[$item['upgrade_type_id']]['version']['ctime']?></td>
                                            <td><?php echo $this->version_list[$item['upgrade_type_id']]['counts']?></td>
                                            <td class="cl0b9600" style="text-align: center;">
                                              <a href="/ezstudio/firmware/mcuversion?id=<?php echo $item['upgrade_type_id']?>">版本</a> | <a target="_blank" href="<?php echo $this->version_list[$item['upgrade_type_id']]['version']['file_path']?>">下载</a>
                                              </td>
                                          </tr>
                                         	<?php endforeach;?>
                                         	<?php else:?>
                                         	<tr><td colspan="9" style="text-align: center;">暂无记录</td></tr>
                                         <?php endif;?>
                                         </tbody>
                                   </table>
                                </div>
               <?php echo $this->paginationControl($this->pagenation, 'Elastic', 'pagelist.phtml',array('base_url'=>$this->base_url)); ?>
          </div>
 </div>

<script language="javascript" type="text/javascript">
	$(function () {
		$('#search').click(function () {
			$('#search_form').submit();
		});
	});
</script>