<!--页面位置-->
<link type="text/css" rel="stylesheet" href="<?php echo $this->static;?>/styles/jquery.mCustomScrollbar.min.css" />
<script type="text/javascript" src="<?php echo $this->static;?>/js/jquery.mCustomScrollbar.min.js"></script>
<script type="text/javascript" src="<?php echo $this->static;?>/js/jquery.form.js"></script>
<h3 class="location f14"><?php echo $this->menu('添加资源', '/ezstudio/ota/list'); ?></h3>
	<form class="cmxform"  action="" method="post" id="form_firmware">
			<table class="detail_tabel remote_table f14 mt20">
               <tbody>
            	<tr>
                    <th>资源信息</th>
                    <th></th>
                </tr>
            	<tr class="system_drop">
                    <td>资源类型：</td>
                    <td>
                        <select id="ota_type" class="cpy_style product_assort mt_12" name ="resource[ota_type]">
                          <option value="">选择资源类型</option>
                          <?php foreach ($this->ota_type as $k=>$v) :?>
                               <option value="<?php echo $v['id'];?>"><?php echo $v['name'];?></option>
                          <?php endforeach;?>
                        </select>
                    </td>
                </tr>
                <tr>
                    <td>资源名称：</td>
                    <td>
                        <input type="text" class="cpy_name" id="name"  name ="resource[name]" value="">
                    </td>
                </tr>
                <tr>
                    <td>资源标识：</td>
                    <td>
                        <input type="text" class="cpy_name" id="label"  name ="resource[label]" value="">
                    </td>
                </tr>
                <tr>
                    <td>资源描述：</td>
                    <td>
                        <textarea rows="10" cols="60" class="text_cls wp60" id="description" name="resource[description]"></textarea>
                    </td>
                </tr>
                </tbody>
                </table>
            <div class="mt36 mb24 tr">
                <a  onfocus="blur();" href="javascript:void(0)" id="cancel_btn" class="f16 clF fr ml16 tc search_btn grey_btn" >返 回</a>
                <a  onfocus="blur();" href="javascript:void(0)" id="sub_btn" class="f16 clF tc search_btn" >提 交</a>
            </div>
</form>
<div id="message_dialog" style="display:none;" title="系统提醒">
    <p class="message_text" id="sys_notice">数据保存成功！</p>
    <a id="close_message"  onfocus="blur();" class="f16 clF tc search_btn brue_btn" href="javascript:void(0)" >确 定</a>
</div>

<div id="confirm_dialog" style="display:none;" title="系统提醒">
    <p class="message_text">您确定删除此上传的文件吗？</p>
</div>

<script language="javascript" type="text/javascript">
    $(function() {
        var G_validate = false;
        var img_container = '';
    	$( "#confirm_dialog" ).dialog({
            autoOpen: false,
            width: 540,
            height: 240,
            show: {
                effect: "blind",
                duration: 300
            },
            hide: {
                effect: null,
                duration: 500
            },
            dialogClass: "my_message_dialog",
            modal: true,
            buttons: {
                "取消": function() {
                    $( this ).dialog( "close" );
                },
                "确定": function() {
                	img_container.remove(); // 移除需要删除的图片
                	$( this ).dialog( "close" );
                }
            }
        });
        
        $( "#message_dialog" ).dialog({
            autoOpen: false,
            width: 540,
            height: 240,
            show: {
                effect: "blind",
                duration: 300
            },
            hide: {
                effect: null,
                duration: 500
            },
            dialogClass: "my_message_dialog",
            modal: true
        });
        
        $("#close_message").on("click",function() {
        	$( "#message_dialog" ).dialog( "close" );
            if(G_validate) {
				// location.href = '/product/firmware/commversion?id='+$('#firmware_id').val();
            }
            if($('#sys_notice').text() == '数据保存成功！'){
                location.href = '/ezstudio/ota/list/rand/'+Math.ceil(Math.random()*10);
            }
            return false;
        });
        jQuery.validator.addMethod("label", function(value, element) {
            var label = /^\w{2,50}$/;
            return this.optional(element) || (label.test(value));
        }, "\u6807\u7b7e\u53ea\u80fd\u542b\u6709\u6570\u5b57\u3001\u5b57\u6bcd\u548c\u4e0b\u5212\u7ebf\uff08\u793a\u4f8b\u003a\u0075\u0073\u0065\u0072\u005f\u006e\u0061\u006d\u0065\u005f\u0076\u0031\uff09");
        // 上述提示为：标签只能含有数字、字母和下划线（示例:user_name_v1）
       $('#form_firmware').validate({
    		rules: {
    			'resource[name]': {
    				maxlength:20,
    				minlength:2,
    				required: true
    			},
    			'resource[label]': {
    				maxlength:50,
    				minlength:2,
                    label:true,
    				required: true
    			},
    			'resource[ota_type]': {
    				required: true
    			},
    			'resource[description]': {
    				maxlength:100,
    				minlength:5
    			}
    		},
    		messages: {   //自定义提示信息
    			//old_password: "原密码输入错误",
    		},
    		ignore : '',
            errorPlacement: function(error, element) {
                error.appendTo(element.parents('td'));
            }
    	});	
		// 提交表单
    	$('#sub_btn').click(function () {
			if($('#form_firmware').valid()) {
				$('#form_firmware').ajaxSubmit({
					url:'/ezstudio/ota/add', //提交给数据保存接口
					type:'POST',
					dataType: 'json',
					success: function (result) {
						if(result.status == 200) {
							G_validate =  true;
							$('#sys_notice').text('数据保存成功！');
						} else if(result.status == 500) {
							G_validate =  false;
							$('#sys_notice').text('系统繁忙，请稍后再试！');
						} else if(result.msg == 505) {
							G_validate =  false;
							$('#sys_notice').text('亲，你没有这个操作的权限！');
						} else {
							G_validate =  false;
							$('#sys_notice').text(result.msg);
						}
						$( "#message_dialog" ).dialog( "open" );
						return ;
					}
				});
				return false;
			}
		});
		$('#cancel_btn').click(function () {
			// history.go(-1);
            location.href = '/ezstudio/ota/list/rand/'+Math.ceil(Math.random()*10);
		});
		$(document).on('click','li[delete_upload]',function () {
			$( "#confirm_dialog" ).dialog( "open" );
			img_container = $(this);
		});
			
	});
</script>
