<link rel="stylesheet" type="text/css" href="<?php echo $this->static;?>/js/libs/easyui/themes/default/easyui.css" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->static;?>/js/libs/easyui/themes/icon.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->static;?>/styles/base.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->static;?>/styles/jquery-ui.min.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->static;?>/styles/dropkick.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->static;?>/styles/oss.css" />
<script src="<?php echo $this->static;?>/js/jquery.js" type="text/javascript"></script>
<script type="text/javascript" src="<?php echo $this->static;?>/js/cms.js"></script>
<script type="text/javascript" src="<?php echo $this->static;?>/js/jquery.dropkick-min.js"></script>
<script type="text/javascript" src="<?php echo $this->static;?>/js/common.js"></script>
<script src="<?php echo $this->static;?>/js/libs/easyui/jquery.easyui.js"></script>
<script src="<?php echo $this->static;?>/js/libs/easyui/easyui-lang-zh_CN.js"></script>
<script>
$(function(){
       $(".product_assort").dropkick();
       $(".cang_assort").dropkick();
})
</script>