<!--页面位置-->
<h3 class="location f14">
	<?php echo $this->menu("审核公告",'/enterprise/announce/index'); ?>
</h3>
<form action="/enterprise/announce/audit" id="check_form_new"
	method="post">
	<table class="detail_tabel f14 mt20">
		<tr>
			<th>公告内容</th>
			<th></th>
		</tr>
		<tr>
			<td>公告标题：</td>
			<td><?php echo $this->escape($this->info['title'])?></td>
		</tr>

		<tr>
			<td>内容详情：</td>
			<td class="notice_content">
				<?php echo stripcslashes($this->info['content'])?>
			</td>
		</tr>

		<tr>
			<th>发送设置</th>
			<th></th>
		</tr>
		<tr>
			<td>发送对象：</td>
			<td class="system_drop"><?php 
                   if(empty($this->info['enterprise_ids'])):
                       echo '所有厂商';
                   else:
                       echo $this->info['enterprise_name'];
                   endif;
               ?>
			</td>
		</tr>
		<tr>
			<td>发送时间：</td>
			<td class="system_drop"><?php echo $this->info['actual_time']?>
			</td>
		</tr>
		<tr>
			<th>审核结论</th>
			<th></th>
		</tr>
		<tr>
			<td>审核结论：</td>
			<td><input type="radio" name="pass" checked="checked"
				value="audit_success" /><label for="message">通过</label> <input
				type="radio" name="pass" class="ml56" value="audit_failed" /><label
				for="e-mail">不通过</label></td>
		</tr>
		<tr class="h170">
			<td>审核意见：</td>
			<td><textarea class="text_cls" name="remark" cols="40" rows="6"
					id="remark"></textarea>（限120字）</td>
			<input type="hidden" name="id" id="id"
				value="<?php echo $this->info['id']; ?>">
		</tr>
	</table>
</form>
<div class="mt36 mb24 tr">
	<a href="javascript:;" id="cancel_btn"
		class="f16 clF fr ml16 tc search_btn grey_btn">返 回</a> <a
		href="javascript:;" id="submit_btn" class="f16 clF tc search_btn">提交</a>
</div>
<div id="message_dialog" style="display: none;" title="系统提醒">
	<p class="message_text"></p>
</div>
<style>
.notice_content h1{ font-size:2em; margin:0.67em 0; }
.notice_content h2{ font-size:1.8em; margin:0.5em 0; }
.notice_content h3{ font-size:1.5em; margin:0.5em 0; }
.notice_content h4{ font-size:1.2em; margin:0.5em 0;color:#333; }
.notice_content h5{ font-size:1.2em; margin:0.5em 0; }
.notice_content h6{ font-size:1em; margin:0.5em 0; }
.notice_content ul {list-style-type: disc; padding-left:2em; } 
.notice_content ol {list-style-type: decimal; padding-left:2em; }
.notice_content i, em {font-style: italic;}
</style>
<script type="text/javascript">
$(function () {
	$( "#message_dialog" ).dialog({
		  autoOpen: false,
          width: 540,
          height: 240,
          show: {
              effect: "blind",
              duration: 300
          },
          hide: {
              effect: null,
              duration: 500
          },
          dialogClass: "my_message_dialog",
          modal: true,
          buttons: {
              "确定": function() {
              	location.href = '/enterprise/announce/index';
              }
          }
	}); 
	$('#cancel_btn').click(function(){
	  	window.history.go(-1); 
	});

	$('#check_form_new').validate({
		rules: {
			'remark': {
				maxlength:50,
                minlength:2
			},
			'pass': {
				required:true,
			}
		},
        errorPlacement: function(error, element) {
            error.appendTo(element.parent());
        },
		submitHandler : function(){
            // 提交前检查数据
            var pass_val = $('input[name="pass"]:checked').val();
            var remark_val = $('#remark').val();
            var alert_msg = '审核结论和审核意见都需要填写';
            if(typeof(pass_val) == "undefined"){
                return alert(alert_msg);
            }
            var param = $('#check_form_new').serialize(); 
            $.post('/enterprise/announce/audit', param, function (result) {
                if(result.status == 200) {
                    $('.message_text').text('保存成功！');
                    return $( "#message_dialog" ).dialog( "open" );
                } else {
                    $('.message_text').text('服务器忙，请重试！');
                    return $( "#message_dialog" ).dialog( "open" );
                }
            },'json');
		}
	});
	
	$('#submit_btn').click(function(){
        $('#check_form_new').submit();
	});
});
</script>