<!--页面位置-->
<h3 class="location f14">
	<h3 class="location f14">
		<?php echo $this->menu(); ?>
	</h3>
</h3>
<form action="" method="get" id="search_form">
	<div class="product_detail_search clearfix mt22 search_div">



		<div class="fl system_drop clearfix">
			<select id="cang_assort" class="cpy_style cang_assort"
				name="search[enterprise_id]" style="width: 185px;">
				<option value="">发送对象</option>
				<?php foreach ($this->enterprises as $k=>$v):?>
				<option value="<?php echo $k;?>"
					<?php if($k == $this->search['enterprise_id']):?>
					selected="selected" <?php endif;?>>
					<?php echo mb_strimwidth($v,0,26,'...');?>
				</option>
				<?php endforeach;?>
			</select>
		</div>

		<div class="fl system_drop clearfix">
			<select class="cpy_style product_assort" name="search[status]"
				style="width: 120px;">
				<option value="">发送状态</option>
				<?php foreach ($this->status as $key=>$name) {?>
				<option value="<?php echo $key;?>"
					<?php if(!empty($this->search['status']) && $key == $this->search['status']):?>
					selected="selected" <?php endif;?>>
					<?php echo $this->t($name);?>
				</option>
				<?php }?>
			</select>
		</div>

		<div class="fl clearfix">
			<input type="text" name="search[start]" class="time_pick"
				id="timer_from" readonly /> <label> - </label> <input type="text"
				name="search[end]" class="time_pick" id="timer_to" readonly />
		</div>


		<div class="console_search_wrap fr">
			<a class="search_icon_btn f16 clF tc ml10" onFocus="blur();"
				id="search_submit" href="javascript:;"><i class="find_icon"></i>查
				询</a>
		</div>
	</div>
</form>

<div class="product_detail_display">
	<div class="product_detail_display_tab_wrap clearfix">

		<a id="add_version" class="f16 clF tc search_btn fr  mr10 nmt10"
			href="<?php echo $this->url(array('action' =>'add'));?>">创建公告</a>
	</div>
	<div class="product_table mt24 f14">
		<table class="table_s tc tc_left auto_table_len" width="100%"
			border="0">
			<thead>
				<tr>
					<td width="60px">ID</td>
					<td><?php echo $this->t('announce_title'); ?></td>
					<td><?php echo $this->t('announce_to'); ?></td>
					<td width="130px"><?php echo $this->t('announce_send_time'); ?></td>
					<td width="100px"><?php echo $this->t('announce_status'); ?></td>
					<td style="text-align: right; width: 60px"><?php echo $this->t('announce_readed'); ?></td>
					<td style="text-align: center; width: 100px"><?php echo $this->t('control'); ?></td>
				</tr>
			</thead>
			<tbody>
				<?php if(!empty($this->results['rows'])) :?>
				<?php foreach ($this->results['rows'] as $row) {?>
				<tr>
					<td><?php echo $row['id'];?></td>
					<td title="<?php if($row['title']) { echo $row['title'];}?>"><?php if($row['title']) { echo $row['title'];}?></td>
					<td title="<?php echo $row['enterprise_name']?>"><?php echo $row['enterprise_name'];?></td>
					<td><?php echo $row['actual_time'];?></td>
					<td><?php if($row['status'] == Model_Announce::STATUS_AUDIT_FAILED):?><font
						color="#c8c8c8"><?php echo $row['status_name'];?></font> <?php elseif($row['status']==Model_Announce::STATUS_PENDING):?>
						<font color="red"><?php echo $row['status_name'];?></font> <?php elseif(in_array($row['status'],array(Model_Announce::STATUS_FINISHED,Model_Announce::STATUS_AUDIT_SUCCESS))):?>
						已发送 <?php else:?> <?php echo $row['status_name'];?> <?php endif;?></td>
					<td style="text-align: right;"><?php echo $row['portion'];?></td>
					<td class="cl0b9600" style="text-align: center;"><?php if($row['status'] == Model_Announce::STATUS_PENDING):?>
						<a
						href="<?php echo $this->url(array('action' => 'audit' , 'id' => $row['id']));?>"
						class="check_detail cl0b9600">审核</a> <?php elseif($row['status'] == Model_Announce::STATUS_AUDIT_FAILED):?>
						<a
						href="<?php echo $this->url(array('action' => 'edit' , 'id' => $row['id']));?>"
						class="check_detail cl0b9600">修改</a> &nbsp;&nbsp;|&nbsp;&nbsp; <a
						href="javascript:;" id="id_<?php echo $row['id'];?>"
						class="del_msg cl0b9600">删除</a> <?php else:?> <a
						href="<?php echo $this->url(array('action' => 'view' , 'id' => $row['id']));?>"
						class="check_detail cl0b9600">查看</a> <?php endif;?></td>
				</tr>
				<?php }?>
				<?php else:?>
				<tr>
					<td colspan="7" style="text-align: center;">暂无记录</td>
				</tr>
				<?php endif;?>
			</tbody>
		</table>
	</div>
	<?php echo $this->paginationControl($this->pagenation, 'Elastic', 'pagelist.phtml',array('base_url'=>$this->base_url)); ?>
	<div id="confirm_dialog" style="display: none;" title="系统提醒">
		<p class="message_text">您确认删除此条记录吗？</p>
	</div>
</div>
<div></div>
<div id="manager_div" style="display: none;" title="厂商管理">
	<form class="cmxform"
		action="<?php echo $this->url(array('controller'=>'index', 'action' =>'manager'));?>"
		method="post" id="manage_form">
		<table class="detail_tabel form_table f14">
			<tr>
				<td>当前状态：</td>
				<td id="current_status"></td>
			</tr>

			<tr class="h60">
				<td>处理措施：</td>
				<td><input type="radio" name="pass" checked="checked" value="0" /><label>启用</label>
					<input type="radio" name="pass" class="ml56" value="1" /><label>冻结</label>
				</td>
			</tr>
			<tr class="h170">
				<td>管理备注：</td>
				<td><textarea class="text_cls" name="remark" cols="40" rows="6"
						id="remark"></textarea></td>
			</tr>
			<tr>
				<td>结果通知：</td>
				<td><input type="checkbox" checked="checked" name="message[]"
					value="msg" /><label for="message">短信</label> <input
					type="checkbox" checked="checked" name="message[]" class="ml56"
					value="email" /><label for="e-mail">邮箱</label></td>
				<input type="hidden" name="enterprise_id" id="enterprise_id">
			</tr>
		</table>
	</form>
</div>
<script type="text/javascript">
    $(document).ready(function(){
        <?php if($this->search['start']):?>
        var time_from = $("#timer_from").datepicker( 'setDate' , "<?php echo $this->search['start'];?>" );
        time_from.onClose = function(selectedDate){
            $( "#timer_to" ).datepicker( "option", "minDate", selectedDate );
        }
        <?php endif;?>
        <?php if($this->search['end']):?>
        var timer_to = $("#timer_to").datepicker( 'setDate' , "<?php echo $this->search['end'];?>" );
        timer_to.onClose = function(selectedDate){
            $( "#timer_from" ).datepicker( "option", "maxDate", selectedDate );
        }
        <?php endif;?>

        var msg_id = 0;
        $( "#confirm_dialog" ).dialog({
            autoOpen: false,
            width: 555,
            dialogClass: "my-dialog",
            modal: true,
            show: {
                effect: "blind",
                duration: 300
            },
            hide: {
                effect: null,
                duration: 500
            },
            buttons: {
                "取消": function() {
                    $( this ).dialog( "close" );
                },
                "确定": function() {
                    if(msg_id) {
                        $.post('/enterprise/announce/delete/', {id:msg_id}, function(e) {
                            location.reload();
                        },'json');
                    }
                }
            }
        });

        $('.del_msg').click(function(e){
            var target = $(e.target);
            var id = target.attr('id').split('_')[1];
            msg_id = id;
            $( "#confirm_dialog" ).dialog('open');
        });
    });
</script>
