<div class="product_detail_display">
	<form id="search_form" action="">
		<div class="product_detail_search clearfix">
			<div class="fl system_drop clearfix">
				<label class="fl mt4">厂商：</label> <select id="enterprise_id"
					class="cpy_style cang_assort product_assort"
					name="search[enterprise_id]" style="width: 120px;">
					<option value="">选择厂商</option>
					<?php foreach ($this->enterprises as $k=>$v) {?>
					<option value="<?php echo $k;?>"
						<?php if($k == $this->search['enterprise_id']):?>
						selected="selected" <?php endif;?>>
						<?php echo mb_strimwidth($v,0,20,'...');?>
					</option>
					<?php }?>
				</select>
			</div>

			<div class="console_search_wrap fr mr10">
				<a style="color: #FFFFFF;" class="search_icon_btn f16 clF tc"
					onFocus="blur();" id="search_submit" href="javascript:;"><i
					class="find_icon"></i>查 询</a>
			</div>
		</div>
	</form>
	<div class="product_table mt10 f14">
		<table class="table_s tc" width="100%" border="0">
			<thead>
				<tr>
					<td><input type="checkbox" value="<?php echo $v['id'];?>"
						id="checkAll"></td>
					<td>名称</td>
					<td>类型</td>
				</tr>
			</thead>
			<tbody>
				<?php if($this->paginator->getTotalItemCount() >0) :?>
				<?php foreach ($this->paginator as $v):?>
				<tr>
					<td><input type="checkbox" class="checkbox"
						value="<?php echo $v['id'];?>"></td>
					<td><?php if($v['company_name']) { echo mb_strimwidth( $v['company_name'],0,20,'...');} else { echo '遥控e族';};?>
					</td>
					<td><?php echo $v['user_type'];?></td>

				</tr>
				<?php endforeach; ?>
				<?php else: ?>
				<tr>
					<td colspan="5">暂无记录</td>
				</tr>
				<?php endif;?>
			</tbody>
		</table>
	</div>
	<?php echo $this->paginationControl($this->pagenation, 'Elastic', 'pagelist.phtml',array('base_url'=>$this->base_url)); ?>
</div>
<script type="text/javascript">
        $(document).ready(function(){
			$("#enterprise_id").dropkick();
			$("#produt_assort").dropkick();
        	$('.checkbox').each(function(){
            	var current = $(this);
            	if(products_map.containsKey(current.val())) {
            		$(this).attr('checked', true);
            	}
             })
            $('#checkAll').click(function(){
            	var current = $(this);
                $('.checkbox').each(function(){
                    var p_name = $(this).parent().next().text();
                    var val = $(this).val();
                     if(current.is(':checked')) {
                         $(this).prop('checked', true);
                         if(val) products_map.put(val, p_name);
                     } else {
                         $(this).prop('checked', false);
                         if(val) products_map.remove(val, p_name);
                     }
                });
            })
            $('.checkbox').click(function(){
           	     var current = $(this);
           	     var p_name = current.parent().next().text();
           	     var val = current.val();
           	     if (val && current.is(':checked') == true) {
           		     products_map.put(val, p_name);
           	     } else if(val && current.is(':checked') == false){
           		     products_map.remove(val, p_name);
           	     }
            });
            $('#search_submit').click(function(){
                   var params = $('#search_form').serialize();
       		       $( "#product_list_div").load('/enterprise/announce/enterprise',params,function(){
    			 
    		       })
             });
           $('.my-navigation a').click(function(){
               var href = $(this).attr('href');
               var url = '/enterprise/announce/enterprise' + href;
               if(href.substring(href.indexOf('&')).length <= 6)
                   return false;
   		       $( "#product_list_div").load(url,function(){
		       })
		       return false;
           });
           $('.simple-pagination-select-specific-page').unbind('change');
           $('.simple-pagination-select-specific-page').change(function(){
        		var href =  $(this).find('option:selected').attr('href');
        		var url = '/enterprise/announce/enterprise' + href;
    		       $( "#product_list_div").load(url);
        	})
         })
        </script>