<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title><?php echo $this->translate('site_name'); ?></title>
<?php echo $this->render('static.phtml');?>
</head>
<body>
<div class="header">
    <div class="header-content">
        <?php echo $this->render('header.phtml');?>
   </div>
</div>
<div class="body clearfix">
<!--备注信息-->
<div id="aside-menu" class="aside">
      <?php /** echo $this->render('left-menu.phtml'); **/ ?>
</div><!-- #EndLibraryItem -->
<div id="main-body" class="main">
<div class="content clearfix">
     <h3>亲，您暂时没有此页面的权限哦!</h3>
     <h3><a href="javascript:history.go(-1);">返回>> </a></h3> 
</div>
   </div>
    </div>
</body>
</html>