<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Zend Framework Default Application</title>
</head>
<body>
  

  <?php if (isset($this->exception)): ?>
  
  <h2>亲，出错啦！</h2>
  <h3><?php echo $this->message ?></h3>
  <?php endif ?>

</body>
</html>
