                   <div class="product_detail_display">
                           <div class="product_table mt10 f14">
                                       <table class="table_s tc" width="100%" border="0">
                                         <thead>
                                          <tr>                        
                                            <td></td>
                                            <td>平台名称</td>
                                            <td>平台标识</td>
                                          </tr>
                                         </thead>
                                         <tbody>
           <?php if(count($this->platforms) >0) :?>
                        <?php foreach ($this->platforms as $k => $v):?>
                                             
                        <tr>
                            <?php if($this->select_model == 'radio'): ?>
                                <td><input type="radio" name='sel' class="checkbox" value="<?php echo $k;?>"></td>
                            <?php else: ?>
                                <td><input type="checkbox"  class="checkbox" value="<?php echo $k;?>"></td>
                            <?php endif; ?>
                            
                            <td title="<?php echo $v;?>"><?php echo $v;?></td>
                            <td><?php echo $k;?></td>
                        </tr>
                        <?php endforeach; ?>
             <?php else: ?>
                        <tr><td colspan="3">暂无记录</td></tr>
             <?php endif;?>
                                         </tbody>
                                   </table>
                          </div>
                 </div>
                <input type='hidden' value='<?php echo $this->select_model; ?>' name='select_model' id='select_model' />
        <script>
        $(document).ready(function(){
        	$('.checkbox').each(function(){
            	var current = $(this);
            	if(platforms_map.containsKey(current.val())) {
            		$(this).attr('checked', true);
            	}
             })
            $('#checkAll').click(function(){
                var current = $(this)
                $('.checkbox').each(function(){
               	 if(current.is(':checked')) {
               		 $(this).prop('checked', true);
               	 } else {
               		 $(this).prop('checked', false);
               	 }
                });
            })
            $('.checkbox').click(function(){
           	     var current = $(this);
           	     var p_name = current.parent().next().attr('title');
           	     var val = current.val();
                 var model = $('#select_model').val();
                 if(model == 'radio'){
                    platforms_map.clear()
                    if (val && current.is(':checked') == true) {
                        platforms_map.put(val, p_name);
                    }
                 }else{
                    if (val && current.is(':checked') == true) {
                        platforms_map.put(val, p_name);
                    } else if(val && current.is(':checked') == false){
                        platforms_map.remove(val, p_name);
                    } 
                 }
            });
           $('.my-navigation a').click(function(){
               var href = $(this).attr('href');
               if(href.substring(href.indexOf('&')).length <= 27)
                   return false;
               var url = '/operation/usermessage/platforms' + href;
   		       $( "#platform_list_div").load(url,function(){
		       })
		       return false;
           });
           $('.simple-pagination-select-specific-page').unbind('change');
           $('.simple-pagination-select-specific-page').change(function(){
        		var href =  $(this).find('option:selected').attr('href');
        	    var url = '/operation/usermessage/platforms' + href;
    		       $( "#platform_list_div").load(url);
        	})
         })
        </script>