 <link type="text/css" rel="stylesheet" href="<?php echo $this->static;?>/styles/treeGrid.css" />
 <link type="text/css" rel="stylesheet" href="<?php echo $this->static;?>/styles/oss.css" />
<!--页面位置-->
<h3 class="location f14"><?php echo $this->menu(); ?></h3>
<div id="table_warp" class="product_detail mt22">
	<div class="product_detail_search clearfix">
    	<div class="console_search_wrap fr mr10"><a  href="javascript:;" class="f16 clF tc search_btn ml16" id="add_category_btn">添加品类</a></div>
    </div>
    <div class="mt24 clearfix"></div>
    <table  id="treeGrid" resizeWidth="resizeWidth" resizeHeight="resizeHeight" rowNum="false" height="500" datasource="treeGridDatasource" treeField="name" onCellStyleRender="onCellStyleRender" onCellContentRender="onCellContentRender">
        <thead>
        <tr>
            <th field="id" width="60" align="left" style="text-align: left">品类ID</th>
            <th field="name" width="200"  align="left" style="text-align: left">产品品类</th>
            <th field="ctime" width="180" align="left" style="text-align: left">添加时间</th>
            <th field="has_product" width="180" align="right" style="text-align: left">产品数</th>
            <th field="active_num" width="180" align="right" style="text-align: left">激活量</th>
            <th field="sort" width="180" align="right" style="text-align: left">排序</th>
            <th field="operate" width="180" align="center" style="text-align: center">操作</th>
        </tr>
        </thead>
    </table>
</div>
 <div id="category_div"  title="添加品类" style="display:none;">
 <form  class="cmxform"  action="<?php echo $this->url(array('controller'=>'category', 'action' =>'add'));?>" method="post" id="category_form">
    <table class="detail_tabel form_table f14 mt40">
        <tr>
            <td style="width:25%">品类名称:</td>
            <td><input type="text" style="width:296px;" class="cpy_name" name="name"/></td>
        </tr>  
        <tr>
            <td>上级品类:</td>
            <td id="product_enterprise"  class="system_drop pb14">
            	<select id="cang_assort" class="cpy_style cang_assort" name="parent_id" style="width:252px;" >
	                  <?php foreach ($this->category as $v) :?>
                             <option value="<?php echo $v['id'];?>" <?php if($v['id'] == $this->search['category']):?>selected="selected" <?php endif;?>><?php echo $v['levelstr'] . $v['name'];?></option>
                        <?php endforeach;?>
                </select>
            </td>
        </tr> 
        <tr>
            <td>排序:</td>
            <td id="product_check_type">
                <input style="width:100px;" type="text" class="cpy_name" name="sort" />&nbsp;<span style="color:gray;">（大于0的整数）</span>
            </td>
        </tr>
        <tr>
            <td></td>
            <td style="color:gray;">
                注：同级数字越大，排序越前；相同，则新添加在前
            </td>
        </tr>
        <tr  class="h170">
            <td>品类描述:</td>
            <td><textarea class="text_cls" id="description" name="description" cols="40" rows="8"></textarea></td>
        </tr>
    </table>
 </form>
</div>
 <div id="message_dialog" style="display:none;" title="系统提醒">
      <p class="message_text">无法删除，该品类下已包含产品，请更改后再删除！</p>
      <a id="close_message"  href="javascript:;" class="f16 clF tc search_btn brue_btn" >确 定</a>
</div>
 <script type="text/javascript" src="<?php echo $this->static;?>/js/treeGrid.min.js"></script>
 <script>
 $(function (){
//   渲染树表格
   $('#category_form').validate({
	rules: {
		'description': {
			maxlength:100
		},
		'name' : {
			required: true,
			maxlength : 20
		},
		'sort' : {
			digits : true,
			required: true,
			maxlength : 5,
			min:1
		}
	}
   });
   $(".cang_assort").dropkick();
   $( "#category_div" ).dialog({
	    autoOpen: false,
	    width: 655,
	    dialogClass: "my-dialog hidden-dialog",
        modal: true,
	    show: {
	        effect: "blind",
	        duration: 300
	    },
	    hide: {
	        effect: null,
	        duration: 500
	    },
	    buttons: {
	        "取消": function() {
	            $( this ).dialog( "close" );
	        },
	        "确定": function() {
	            $('#category_form').submit();
	        }
	    }
	});
	$('#add_category_btn').click(function(){
		var category_div = $('#category_div');
        // 重置表单信息
        $('#category_form')[0].reset();
		category_div.find('form').attr('action', '/product/category/add');
	    $( "#category_div").dialog("option","title", "添加品类").dialog( "open" );
	    return false;
	});
	$( "#message_dialog" ).dialog({
		  autoOpen: false,
          width: 540,
          height: 240,
          show: {
              effect: "blind",
              duration: 300
          },
          hide: {
              effect: null,
              duration: 500
          },
          dialogClass: "my_message_dialog",
          modal: true
	}); 
	TreeGrid.scan("#treeGrid");
	$('#close_message').click(function(){
		$( "#message_dialog" ).dialog( "close" );
    });
});
//渲染 最后一个操作列的展示
function onCellContentRender(value,rowData,field){
   if(field ==="operate") {
       return  '<a href="#" class="download_a " onclick="edit_node('+ rowData.id + ')">编辑</a>&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;<a href="#" class="download_a " onclick="delete_node('+ rowData.id +')" >删除</a>';
   }
   
   if((field === "active_num" || field === "has_product") && value === "") {
	   return  '0';
   }
};
//渲染中间散列的字体颜色
function onCellStyleRender(value,rowData,field){
   if(field==="PercentComplete" || field==="Duration" || field==="Start" ){
       return 'color:#acacac';
   }
   if(field ==="operate"){
       return 'color:#216ed9';
   }
};
//定义表格的宽度
function resizeWidth(){
   return $("#table_warp").width() - 18;
};
//定义表格的高度
function resizeHeight(){
   return $(window).height() - 200;
}
//设置表格的数据
function treeGridDatasource (obj){
	$.get('/product/category/treedata', function(data){
		if(data.status == 200) {
			obj.setDatasource(TreeGrid.listToTree(data.result,"id","parent_id"));
		} else if (data.msg == 505) {
            $('#message_dialog .message_text').text('亲，你没有这个操作的权限！');
            $("#message_dialog").dialog("open");
        }
	},'json');  
}
/**
 * 编辑
 */
function edit_node(v) {
	$.get('/product/category/info',{id:v}, function(data){
		if(data.status == 200) {
			var category_div = $('#category_div');
			//category_div.dialog()；
            // 处理表单数据置空的问题  by etong <zhoufeng@wondershare.cn> 2014/08/05 13:52
            // --start
            category_div.find('form')[0].reset();
            // --end
            
			category_div.find('form').attr('action', '/product/category/add?id=' + v);
			var res = data.result;
			category_div.find('input[name="name"]').val(res.name);
			category_div.find('input[name="sort"]').val(res.sort);
            // 处理添加dropkick后的select选中问题 by etong <zhoufeng@wondershare.cn> 2014/08/05 13:52
            // --start
            $('a[data-dk-dropdown-value="'+res.parent_id+'"]').click();
            // --end
            category_div.find('#cang_assort').val(res.parent_id);
			$( "#category_div").dialog("option","title", "编辑品类").dialog("open" ); 
		}
	},'json');
}

/**
 * 删除
 */
function delete_node(v) {
	$.get('/product/category/del', {id:v}, function(data){
		if(data.status == 200) {
			if(data.result == 'del_failed') {
				$( "#message_dialog").dialog( "open" ); 
			} else {
				location.reload();
			}
		} else if (data.msg == 505){
			$('#message_dialog .message_text').text('亲，你没有这个操作的权限！');
			$( "#message_dialog").dialog( "open" );
		}
	},'json');  
}
</script>
 