
<!--页面位置-->
<h3 class="location f14"><?php echo $this->menu(); ?></h3>
<form action="" method="get"  id="search_form">
<div class="product_detail mt22">
   <div class="product_detail_search clearfix">
	   <div class="fl system_drop clearfix">
		   <select id="cang_assort" class="cpy_style cang_assort" name="search[enterprise_id]" style="width: 185px;">
			   <option value="">选择厂商</option>
			 <?php foreach ($this->enterprises as $k=>$v) {?>
			 <option value="<?php echo $k;?>" <?php if($k == $this->search['enterprise_id']):?>selected="selected" <?php endif;?>><?php echo mb_strimwidth($v,0,26,'...');?></option>
			 <?php }?>
		   </select>
	   </div>
		<div class="fl system_drop clearfix">
			<select id="produt_assort" class="cpy_style product_assort" name="search[category]" style="width: 120px;">
				<option value="">选择品类</option>
			 <?php foreach ($this->category as $v) {?>
			 <option value="<?php echo $v['id'];?>" <?php if($v['id'] == $this->search['category']):?>selected="selected" <?php endif;?>><?php echo $v['levelstr'] . mb_strimwidth($v['name'],0,14,'...');?></option>
			 <?php }?>
			</select>
		</div>
		<div class="fl system_drop clearfix">
		   <select class="cpy_style cang_assort" name="search[device_type]" style="width: 120px;">
			   <option value="">设备类型</option>
			 <option value="<?php echo Model_Device::DEVICE_TYPE_TEST;?>" <?php if(!empty($this->search['device_type']) && Model_Device::DEVICE_TYPE_TEST == $this->search['device_type']):?>selected="selected" <?php endif;?>>测试</option>
			 <option value="<?php echo Model_Device::DEVICE_TYPE_FORMAL;?>" <?php if(!empty($this->search['device_type']) && Model_Device::DEVICE_TYPE_FORMAL == $this->search['device_type']):?>selected="selected" <?php endif;?>>正式</option>
		   </select>
	   </div>
		<div class="fl system_drop clearfix">
			<select class="cpy_style product_assort" name="search[status]" style="width: 120px;">
				<option value="">设备状态</option>
			 <?php foreach ($this->status as $key=>$name) {?>
			 <option value="<?php echo $key;?>" <?php if(!empty($this->search['status']) && $key == $this->search['status']):?>selected="selected" <?php endif;?>><?php echo $name;?></option>
			 <?php }?>
			</select>
		</div>
		<div class="fl">
			<input type="text" class="cpy_name w150" id="cpy_name" name="search[device_id]" value="<?php if(!empty($this->search['device_id'])){ echo $this->search['device_id'];}?>" placeholder="请输入设备ID">
		</div>
		<div class="fl">
			<input type="text" class="cpy_name w150" id="dev_name" name="search[name]" value="<?php if(!empty($this->search['name'])){ echo $this->search['name'];}?>" placeholder="请输入设备名">
		</div>
		<div class="console_search_wrap fr"><a class="search_icon_btn f16 clF tc" onFocus="blur();" id="search_submit"  href="javascript:;"><i class="find_icon"></i>查 询</a></div>
   </div>
   </div>
</form>
<div class="product_detail_display" style="margin-bottom: 20px;">  
	<div class="product_table mt24 f14">
	   	<table class="table_s tc tc_left auto_table_len" width="100%" border="0">
				 <thead>
				  <tr>                          
					<td>设备ID</td>
					<td>设备名称</td>
					<td>产品名称（型号）</td>
					<td width="80px">固件版本号</td>
					<td width="60px">设备类型</td>
					<td width="160">厂商</td>
					<td width="130">激活时间</td>
					<td width="60">设备状态</td>
					<td width="100" style="text-align: center;">操作</td>
				  </tr>
				 </thead>
		 <tbody>
		 <?php if($this->paginator->count()):?>
		 <?php foreach ($this->paginator as $row) :?>
		  <tr>
			<td title="<?php echo $row['id'];?>"><?php echo $row['id'];?></td>
			<td title="<?php echo $row['name'];?>"><?php echo $row['name'] ? $row['name'] : '-';?></td>
			<td title="<?php echo $row['p_name'];?>"><?php echo $row['p_name'];?></td>
			<td><?php echo $row['version'];?></td>
			<td style="color:<?php if($row['type'] == Model_Device::DEVICE_TYPE_TEST) { echo 'red';};?>;"><?php echo $this->t($row['type']);?></td>
			<td title="<?php echo $row['company_name'];?>"><?php echo $row['company_name'];?></td>
			<td><?php echo $row['user_activate_time'];?></td>
                    
					<td style="color:<?php if(in_array($row['status'], array(Model_Device::STATUS_DISABLE, Model_Device::STATUS_FAULT))) { echo '#ccc';}?>;">
                        <?php if(in_array($row['status'], array(Model_Device::STATUS_NEW, Model_Device::STATUS_FACT_ACTIVATE))): ?>
                            新的
                        <?php else: ?>
                            <?php echo $this->t($row['status']);?>
                        <?php endif; ?>
                     </td>   
					  <td class="cl0b9600" id="product_ctrl" style="text-align: center;">
				   <a href="<?php echo $this->url( array('action'=>'detail', 'id' => $row['id']));?>">查看</a>
				  <?php if($row['type'] == Model_Device::DEVICE_TYPE_TEST):?> | <a href="javascript:;"  id="id_<?php echo $row['id'];?>" class="del_msg cl0b9600">删除</a><?php endif;?>
			  </td>
		  </tr>
		  <?php endforeach;?>
		  <?php else:?>
		  <tr><td colspan="9" style="text-align: center;">暂无记录</td></tr>
		  <?php endif;?>
		 </tbody>
   	</table>
	</div>
	<?php echo $this->paginationControl($this->paginator, 'Elastic', 'pagelist.phtml',array('base_url'=>$this->base_url)); ?>
</div>
<div id="confirm_dialog" style="display:none;" title="系统提醒">
	<p class="message_text">您确认删除此条记录吗？</p>
	<p><input type="checkbox" id="del_bind_info">同时删除该设备的绑定信息</p>
</div>
<script>
var msg_id = 0;
$( "#confirm_dialog" ).dialog({
    autoOpen: false,
    width: 555,
    dialogClass: "my-dialog",
    modal: true,
    show: {
        effect: "blind",
        duration: 300
    },
    hide: {
        effect: null,
        duration: 500
    },
    buttons: {
        "取消": function() {
            $( this ).dialog( "close" );
        },
        "确定": function() {
        	if(msg_id) {
            	var del_bind_info = $('#del_bind_info:checked').length;
            	$.post('/product/device/delete/', {id:msg_id, del_relation:del_bind_info}, function(e) {
                    location.reload();
    			},'json');
            }
        }
    }
});
$('.del_msg').click(function(e){
	var target = $(e.target);
	var id = target.attr('id').split('_')[1];
	msg_id = id;
	$( "#confirm_dialog" ).dialog('open');
});
</script>