
<!--页面位置-->
<h3 class="location f14"><?php echo $this->menu(); ?></h3>
<div class="product_detail mt22">
   <div class="product_detail_search clearfix">
	   <div class="chart_index fl f14 plantform">
	       <span style="min-width:56px;display:inline-block;text-align: center;" id="id_<?php echo Model_EnterpriseApp::PLANTFORM_ANDROID;?>" <?php if(!empty($this->search['platform']) && $this->search['platform'] == Model_EnterpriseApp::PLANTFORM_ANDROID ):?>class="on"<?php endif;?>>Android</span>
	       <span style="min-width:56px;display:inline-block; text-align: center;" id="id_<?php echo Model_EnterpriseApp::PLANTFORM_IOS;?>" <?php if(!empty($this->search['platform']) && $this->search['platform'] == Model_EnterpriseApp::PLANTFORM_IOS ):?>class="on"<?php endif;?>>iOS</span>
	   </div>
   </div>
</div>
   <div class="product_detail_display">
		 <div class="product_table mt24 f14">
			   <table class="table_s tc tc_left auto_table_len" width="100%" border="0">
				 <thead>
				  <tr>                          
					<td>厂商</td>
					<td>APP名称</td>
					<td width="130px">创建时间</td>
					<td style="text-align: right;width:60px;">版本数</td>
					<td width="100px">最新版本</td>
					<td style="text-align: right;width:80px;">支持产品数</td>
					<td style="text-align: center;width:150px;">操作</td>
				  </tr>
				 </thead>
				 <tbody>
     <?php if(empty($this->results['rows'])): ?>
             <tr>
                 <td colspan="7" style="text-align: center;">暂无记录</td>
             </tr>
     <?php else: ?>
		  <?php foreach ($this->results['rows'] as $row) :?>
				  <tr>
					<td title = "<?php echo $row['company_name']?>"><?php echo $row['company_name'];?><?php //echo mb_strimwidth($row['company_name'],0,40,'...');?></td>
					<td><?php echo $row['name'];?></td>
					<td><?php echo $row['ctime'];?></td>
					<td style="text-align: right;"><?php echo $row['v_num'];?></td>
					<td><?php echo $row['version']?></td>
					<td class="enterprise_num" id="en_<?php echo $row['enterprise_id'];?>" style="text-align: right;">0</td>
					<td class="cl0b9600" id="product_ctrl" style="text-align: center;">
                     <a href="javascript:void(0)" data-label="<?php echo $row['label'];?>" class="check_code cl0b9600" data-this-logo="<?php echo empty($row['logo']) ? '' : $this->baseUrl . $row['logo']?>"
                           data-urlcode="<?php echo urlencode("http://api.1719.com/download/app/?label=".$row['label'])?>" data-url="<?php echo "http://api.1719.com/download/app/?label=".$row['label']?>" v="h">二维码</a>
                        &nbsp;|&nbsp;
					<a href="<?php echo $this->url(array('controller'=>'enapp', 'action' =>'detail', 'appid'=>$row['id'] ));?>"  class="check_detail cl0b9600">查看</a>
					<?php if(!empty($row['upgrade_type_id'])) :?>
							&nbsp;|&nbsp;
							<a target="_blank" href="<?php echo $this->url(array('controller'=>'enapp', 'action' =>'download', 'upgrade_type_id'=>$row['upgrade_type_id'] ));?>" class="check_detail cl0b9600">下载</a>
				   <?php endif;?>
					  </td>
				  </tr>
				  <?php endforeach;?>
       <?php endif; ?>
				 </tbody>
		   </table>
		</div>
	  <?php echo $this->paginationControl($this->pagenation, 'Elastic', 'pagelist.phtml',array('base_url'=>$this->base_url)); ?>
</div>
<div class="qr_pop" >
	<p class="qr_url"><span id="show_mes">企业APP下载页面地址：</span><br /><span id="show_url"></span></p>
    <div class="clearfix mt18">
        <p class="fl"><img id="show_img" src="" width="138" height="138" /></p>
        <ul class="fl ml22 mr26">
            <li>
                <input type="radio" id="size8" name="qr_size" data-width="258" checked="checked" /><label for="size8">8cm * 8cm</label>
            </li>
            <li>
                <input type="radio" id="size12" name="qr_size" data-width="344" /><label for="size12">12cm * 12cm</label>
            </li>
            <li>
                <input type="radio" id="size15" name="qr_size" data-width="430" /><label for="size15">15cm * 15cm</label>
            </li>
            <li>
                <input type="radio" id="size30" name="qr_size" data-width="860" /><label for="size30">30cm * 30cm</label>
            </li>
            <li>
                <input type="radio" id="size50" name="qr_size" data-width="1280" /><label for="size50">50cm * 50cm</label>
            </li>
        </ul>
        <a href="javascript:;" data-target-id="0" data-logo="" target="_blank" class="check_more f14 clF tc fl mt60">二维码下载</a>
    </div>
</div>
 <script>
 $(document).ready(function(){
	 $('.enterprise_num').each(function(){
		 var currentObj = $(this);
		 var id = currentObj.attr('id').split('_')[1];
		 $.post('/product/enapp/getproducts', {enterprise_id:id}, function(res){
			  if(res.status == 200) {
				  currentObj.text(res.result);
			  }
		 }, 'json')
	 });
	 $('.plantform').click(function(e){
		 var target = $(e.target);
		 if(target.is('span')) {
			 var id = target.attr('id');
			 var plantform = id.split('_');
			 var params = {'search[platform]' : plantform[1]};
			 location.href = '/product/enapp/index?' + jQuery.param(params); 
		 }
	 });
	 $("input[type=radio]").click(function(){
         var tar_width = $(this).attr('data-width');
         var label = $('.check_more').attr('data-target-id');
         var tar_logo = $('.check_more').attr('data-logo');
         var link_url = '/product/ezapp/downqcode?width=' + tar_width + '&label=' + label + '&logo=' + tar_logo;
         $('.check_more').attr('href',link_url)
     });

     $(".check_code").attr("v", "h");
     function get_pos(el, t, l) {
         el.css({
             "top": t,
             "left": l,
             "display": "block"
         });
     }

     $(document).on("click", function (event) {
         var $qr_pop = $(event.target).closest(".qr_pop"),
             $qr_pop2 = $(".qr_pop"),
             $qr_more = $(event.target).closest(".check_code");
         if ($qr_more.length && $qr_more.attr("v") == "h") {
             $('#show_img').attr('src','');
             var urlcode = $qr_more.attr('data-urlcode');
             var url = $qr_more.attr('data-url');
             var logo = $qr_more.attr('data-this-logo');
             var label = $qr_more.attr('data-label');
             $("#show_url").text(url);
             var img_url = 'http://api.1719.com/intranet/generate_qr_code/?width=138&height=138&content=' + urlcode + '&logo=' + logo;
             var img_url_err = 'http://api.1719.com/intranet/generate_qr_code/?width=138&height=138&content=' + urlcode;
             $('#show_img').attr('src',img_url).attr('onerror',"javascript:this.src='"+ img_url_err +"';");
             $('.check_more').attr('data-content',urlcode).attr('data-logo',logo).attr('data-target-id',label);
             $('input[type=radio]:first').trigger("click");

             var t = $qr_more.offset().top + $qr_more.height() - 78,
                 l = $qr_more.offset().left - ($qr_pop2.width() - $qr_more.width()*2 + 10)-200;
             get_pos($qr_pop2, t, l);
             $qr_more.attr("v", "s");
         } else if (!$qr_pop.length) {
             $qr_pop2.css("display", "none");
             $('.check_code').attr("v", "h");
         }
     });
 });
 </script>