<!--页面位置-->
 <h3 class="location f14"><?php echo $this->menu('编辑APP', '/product/ezapp/index'); ?></h3>
 <form class="cmxform"  action="<?php echo $_SERVER['REQUEST_URI']?>" method="post" id="form_app">
 <table class="detail_tabel remote_table f14 mt20">
     <tr>
         <th>基本信息</th>
         <th></th>
     </tr>
     <tr>
         <td>APP名称：</td>
         <td>
             <input type="text" name="app[name]"  class="cpy_name wp60" width="70%"  value="<?php echo $this->appinfo['name'];?>" />
         </td>
     </tr>
     <tr>
         <td>系统平台：</td>
         <td>
              <?php echo $this->appinfo['platform'];?>
         </td>
     </tr>
     <tr class="h170">
         <td>应用简介：</td>
         <td>
             <textarea class="text_cls wp60" name="app[description]" cols="40" rows="6"><?php echo $this->appinfo['description'];?></textarea>
         </td>
     </tr>
     <tr class="h150">
         <td>应用icon：</td>
         <td>
             <div class="img_mark_up mr50"  id="fsUploadProgress">
                 <?php if(!empty($this->appinfo['icon'])) {?>
                 <img src="<?php echo $this->uploadServer['baseUrl'] . $this->appinfo['icon'];?>" />
                 <input name="app[icon]" value="<?php echo $this->appinfo['icon'];?>"  type="hidden" id="app_icon">
                 <?php } else {?>
                 <img src="/static/images/rada.png" />
                 <input name="app[icon]" value=""  type="hidden" id="app_icon">
                 <?php }?>
             </div>
             <div id="img_upload_status" style="display: none;"></div>
             <a  id="upload_img" >上传图片</a>
             <input id="btnCancel" type="button" value="取消上传" disabled="disabled" style="display:none" />

             <label class="clFF0 ml20">（*.jpg;*.gif;*.png）</label>
         </td>
     </tr>
     <tr>
         <td>上传截图：</td>
         <td>
             <span id="upload_btn"></span>
             <label class="clFF0 ml20">（*.jpg;*.gif;*.png）</label>
         </td>
     </tr>
     <tr class="h480">
         <td></td>
         <td>
             <div id="custom_scollbar">
                 <ul class="clearfix mt10" id="fsUploadProgress2">
                 <?php if(!empty($this->appinfo['images'])) {?>
                 <?php foreach ($this->appinfo['images'] as $row) {?>
                     <li class="mr10" >
                     <img src="<?php echo $this->uploadServer['baseUrl'] . $row['image'];?>" width="272" height="410" class="cut_make_up" ><span class="delete_img"></span>
                     <input type="hidden" name="app[images][]" value="<?php echo $row['image'];?>">
                     </li>

                     <?php }?>
                 <?php }?>
                 </ul>
             </div>
         </td>
     </tr>
 </table>
 <div class="mt36 mb24 tr">
 	<a  href="javascript:;" class="f16 clF tc search_btn grey_btn fr ml16"  id="cancle_btn">返 回</a>
     <a  href="javascript:;" class="f16 clF tc search_btn fr"  id="submit_btn">提 交</a>
     
 </div>
 </form>
<div id="message_dialog" style="display:none;" title="系统提醒">
    <p class="message_text" id="sys_notice">数据保存成功！</p>
</div>

<div id="confirm_dialog" style="display:none;" title="系统提醒">
    <p class="message_text">您确认删除此上传的文件吗？</p>
</div>
<link type="text/css" rel="stylesheet" href="<?php echo $this->static;?>/styles/jquery.mCustomScrollbar.min.css" />
<script type="text/javascript" src="<?php echo $this->static;?>/js/jquery.mCustomScrollbar.min.js"></script>
<script type="text/javascript" src="<?php echo $this->static;?>/js/jquery.form.js"></script>
<script type="text/javascript" src="<?php echo $this->static;?>/js/libs/swfupload/swfupload.js"></script>
<script type="text/javascript" src="<?php echo $this->static;?>/js/libs/swfupload/swfupload.queue.js"></script>
<script type="text/javascript" src="<?php echo $this->static;?>/js/libs/swfupload/fileprogress.js"></script>
<script type="text/javascript" src="<?php echo $this->static;?>/js/libs/swfupload/handlers.js"></script>
<script>
$.validator.setDefaults({
    submitHandler: function(form) {
    	$(form).ajaxSubmit({
			type:'POST',
			dataType: 'json',
			success: function (result) {
				if(result.status == 200) {
					$('#sys_notice').data('success', true);
					$('#sys_notice').text('数据保存成功！');
				} else if(result.status == 500) {
					$('#sys_notice').text('系统繁忙，请稍后再试！');
				} else if(result.msg == 505) {
					$('#sys_notice').text('亲，你没有这个操作的权限！');
				} else {
					$('#sys_notice').text(result.msg);
				}
				$( "#message_dialog" ).dialog( "open" );
				return ;
			}
		});    
    }
 });
$('#form_app').validate({
		rules: {
			'app[name]': {
				maxlength:50,
				minlength:2,
				required: true
			},
			'app[description]': {
				maxlength:100
			}
		}
});	
    $(function(){
        $('#cancle_btn').click(function(){
            location.href = '/product/ezapp/index';
        });
        var img_container = '';
    	 $( "#message_dialog" ).dialog({
             autoOpen: false,
             width: 540,
             height: 240,
             show: {
                 effect: "blind",
                 duration: 300
             },
             hide: {
                 effect: null,
                 duration: 500
             },
             dialogClass: "my_message_dialog",
             modal: true,
             buttons: {
                 "确定": function() {
                 	$( this ).dialog( "close" );
                 	if($('#sys_notice').data('success')) {
                     	location.href = '/product/ezapp/index';
                 	} else {
                 		location.reload();
                 	}
                 }
             }
         });

    	 $( "#confirm_dialog" ).dialog({
             autoOpen: false,
             width: 540,
             height: 240,
             show: {
                 effect: "blind",
                 duration: 300
             },
             hide: {
                 effect: null,
                 duration: 500
             },
             dialogClass: "my_message_dialog",
             modal: true,
             buttons: {
                 "取消": function() {
                     $( this ).dialog( "close" );
                 },
                 "确定": function() {
                	 img_container.remove();
                 	$( this ).dialog( "close" );
                 }
             }
         });

      	$('#submit_btn').click(function(){
          	$('#form_app').submit();
        });
         $(document).on('click','li[class=mr10]',function () {
    			$( "#confirm_dialog" ).dialog( "open" );
    			img_container = $(this);
        });
     	var settings = {
				flash_url : "<?php echo $this->static;?>/js/libs/swfupload/swfupload.swf",
				upload_url: "/api/upload/index",
				post_params: {"type" : "app"},
				file_size_limit : "5 MB",
				file_types : "*.jpg;*.gif;*.png",
				file_types_description : "All Files",
				file_upload_limit : 50,  //配置上传个数
				file_queue_limit : 0,
				custom_settings : {
					progressTarget : "fsUploadProgress",
					cancelButtonId : "btnCancel",
					ProgressStatusId:'img_upload_status'
				},
				debug: false,
				button_window_mode:'Opaque',
				// Button settings
				button_image_url: "<?php echo $this->static;?>/images/TestImageNoText_65x29.png",
				button_width: "65",
				button_height: "29",
				button_placeholder_id: "upload_img",
				button_text: '<span class="falsh_upload_button">上传</span>',
				button_text_style: '.falsh_upload_button{color:#FFFFFF;}',
				button_text_left_padding: 16,
				button_text_top_padding: 5,
				button_text_top_margin: 10,
				file_queued_handler : fileQueued,
				file_queue_error_handler : fileQueueError,
				file_dialog_complete_handler : fileDialogComplete,
				upload_error_handler : uploadError,
				upload_success_handler : function(file, serverData) {
					try {
						serverData = eval("("+ serverData +")");
						var progress_div_id = this.customSettings.progressTarget;
						var progress = new FileProgress(file, progress_div_id);
						progress.setComplete();
						progress.setStatus("上传成功");
						progress.toggleCancel(false);
						var img = $('#'+progress_div_id).find('img');
						img.attr('src', serverData.result.url );
						$('#app_icon').val( serverData.result.path );
					} catch (ex) {
						this.debug(ex);
					}
				},
				upload_complete_handler : uploadComplete,
				queue_complete_handler : queueComplete
		};
		var swfu = new SWFUpload(settings);

		//swfupload上传文件  图片
    	var settings = {
				flash_url : "<?php echo $this->static;?>/js/libs/swfupload/swfupload.swf",
				upload_url: "/api/upload/index",
				post_params: {"type" : "app"},
				file_size_limit : "5 MB",
				file_types : "*.jpg;*.gif;*.png",
				file_types_description : "All Files",
				file_upload_limit : 50,  //配置上传个数
				file_queue_limit : 0,
				custom_settings : {
					progressTarget : "fsUploadProgress2",
					cancelButtonId : "btnCancel",
					ProgressStatusId:'img_upload_status'
				},
				debug: false,
				// Button settings
				button_image_url: "<?php echo $this->static;?>/images/TestImageNoText_65x29.png",
				button_width: "65",
				button_height: "29",
				button_placeholder_id: "upload_btn",
				button_text: '<span class="falsh_upload_button">上传</span>',
				button_text_style: '.falsh_upload_button{color:#FFFFFF;}',
				button_text_left_padding: 16,
				button_text_top_padding: 5,
				button_text_top_margin: 10,
				file_queued_handler : fileQueued,
				file_queue_error_handler : fileQueueError,
				file_dialog_complete_handler : fileDialogComplete,
				upload_error_handler : uploadError,
				upload_success_handler : function(file, serverData) {
					try {
						serverData = eval("("+ serverData +")");
						var progress_div_id = this.customSettings.progressTarget;
						var progress = new FileProgress(file, progress_div_id);
						progress.setComplete();
						progress.setStatus("上传成功");
						progress.toggleCancel(false);
						var img = '<img  src="'+ serverData.result.url +'" class="cut_make_up" width="272" height="410"><span class="delete_img"></span>';
						var file_hidden = '<input type="hidden" name="app[images][]" value="'+ serverData.result.path +'">';
						var file_container = '<li class="mr10" >'+ img + file_hidden +'</li>';
						$("#"+progress_div_id).append(file_container);
					} catch (ex) {
						this.debug(ex);
					}
				},
				upload_complete_handler : uploadComplete,
				queue_complete_handler : queueComplete
		};
		var swfu = new SWFUpload(settings);
       //图片滑动
		 $("#custom_scollbar").width($("#custom_scollbar").parent().width());
	        var marginLeft= 7,l=$("#custom_scollbar ul li").length,oLiWidth=(parseInt($("#custom_scollbar ul li").eq(0).width())+marginLeft)*l;
	        $("#custom_scollbar ul").width(oLiWidth);
	        $("#custom_scollbar").mCustomScrollbar({
	            axis:"x",
	            theme:"dark-2",
	            scrollInertia:550,
	            scrollbarPosition:"inside"
	        });
    })
</script>